package com.paul.chef.util

object ConstValue{
    const val ADDRESS = "address"
    const val ATTENDANCE = "attendance"
    const val BLOCK_MENU_LIST = "blockMenuList"
    const val BLOCK_REVIEW_LIST = "blockReviewList"
    const val BOOK_SETTING_TYPE = "bookSetting.type"
    const val BOOK_SETTING_CALENDAR_DEFAULT = "bookSetting.calendarDefault"
    const val BOOK_SETTING_USER_SPACE = "bookSetting.userSpace"
    const val BOOK_SETTING_CHEF_SPACE = "bookSetting.chefSpace"
    const val CHEF = "Chef"
    const val CHAT = "Chat"
    const val CHEF_ID = "chefId"
    const val DATE = "date"
    const val DATE_SETTING = "dateSetting"
    const val LAST_MSG = "lastMsg"
    const val LAST_DATA_TYPE = "lastDataType"
    const val LIKE_LIST ="likeList"
    const val MENU = "Menu"
    const val ORDER = "Order"
    const val PROFILE_INFO = "profileInfo"
    const val PROFILE_INFO_EMAIL = "profileInfo.email"
    const val ROOM = "Room"
    const val REVIEW = "Review"
    const val REVIEW_RATING = "reviewRating"
    const val REVIEW_NUMBER = "reviewNumber"
    const val STATUS = "status"
    const val TRANSACTION = "Transaction"
    const val TIME = "time"
    const val USER = "User"
    const val USER_ID = "userId"
}